_main_index:
    locales:  { es: "/", en: "/" }
    pattern:  /
    defaults: { _controller: AitorGarciaMainBundle:Default:preIndex }

main_index:
    locales:  { en: "/home", es: "/portada" }
    defaults: { _controller: AitorGarciaMainBundle:Default:index }
