_index:
    locales:  { es: "/", en: "/" }
    pattern:  /
    defaults: { _controller: AitorGarciaMainBundle:Default:preIndex }

index:
    locales:  { en: "/home", es: "/portada" }
    defaults: { _controller: AitorGarciaMainBundle:Default:index }

_admin:
    resource: "@AitorGarciaMainBundle/Resources/config/admin_routing.yml"
    prefix: /admin
    type: be_simple_i18n
