eo_honeypot:
    storage:
        file:
            enabled: true
            output: "%kernel.root_dir%/logs/eo_honeypot.log"
            output: /var/log/honeypot.log
    redirect:
        enabled: true
        to: "/"
