lunetics_locale:
    allowed_locales: %locales%
    strict_mode: true
    guessing_order:
        - besimple
        - router
        #- query
        - session
        - cookie
        - browser
    cookie:
        set_on_change: true
    switcher:
        template: "AitorGarciaMainBundle:Locale:locale_switcher.html.twig"
