_app:
    resource: "@AitorGarciaAppBundle/Resources/config/routing.yml"
    prefix: /
    type: be_simple_i18n

_portfolio:
    resource: "@AitorGarciaPortfolioBundle/Resources/config/routing.yml"
    prefix: /
    type: be_simple_i18n

_user:
    resource: "@AitorGarciaUserBundle/Resources/config/routing.yml"
    prefix: /
    type: be_simple_i18n
