aitorgarcia_contact:
    resource: "@AitorGarciaContactBundle/Resources/config/routing/i18n.yml"
    prefix:   /
    type: be_simple_i18n

aitorgarcia_main:
    resource: "@AitorGarciaMainBundle/Resources/config/routing/i18n.yml"
    prefix: /
    type: be_simple_i18n

aitorgarcia_portfolio:
    resource: "@AitorGarciaPortfolioBundle/Resources/config/routing/i18n.yml"
    prefix: /
    type: be_simple_i18n

aitorgarcia_user_i18n:
    resource: "@AitorGarciaUserBundle/Resources/config/routing/i18n.yml"
    prefix: /
    type: be_simple_i18n

aitorgarcia_user_default:
    resource: "@AitorGarciaUserBundle/Resources/config/routing/default.yml"
    prefix: /
