_app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /
    type: be_simple_i18n

_portfolio:
    resource: "@PortfolioBundle/Resources/config/routing.yml"
    prefix: /
    type: be_simple_i18n

_admin:
    resource: "@PortfolioBundle/Resources/config/admin_routing.yml"
    prefix: /admin

_user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix: /
    type: be_simple_i18n
