aitorgarcia_blog:
    resource: "@AitorGarciaBlogBundle/Resources/config/routing/frontend_routing.yml"
    prefix:   /
    type: be_simple_i18n

aitorgarcia_contact:
    resource: "@AitorGarciaContactBundle/Resources/config/routing/frontend_routing.yml"
    prefix:   /
    type: be_simple_i18n

aitorgarcia_main:
    resource: "@AitorGarciaMainBundle/Resources/config/routing/frontend_routing.yml"
    prefix: /
    type: be_simple_i18n

aitorgarcia_portfolio:
    resource: "@AitorGarciaPortfolioBundle/Resources/config/routing/frontend_routing.yml"
    prefix: /
    type: be_simple_i18n

aitorgarcia_user:
    resource: "@AitorGarciaUserBundle/Resources/config/routing/frontend_routing.yml"
    prefix: /
    type: be_simple_i18n

aitorgarcia_user_default:
    resource: "@AitorGarciaUserBundle/Resources/config/routing/default.yml"
    prefix: /
