security:
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                csrf_provider: form.csrf_provider
            logout:
                path:   fos_user_security_logout
                target: _index
            remember_me:
                key:      "%secret%"
                lifetime: 2592000 # 30 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
            anonymous:    true
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/(login|iniciar-sesion)$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/(register|registro), role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/(user\/reset-password|usuario\/recuperar-password), role: IS_AUTHENTICATED_ANONYMOUSLY }

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
