stfalcon_tinymce:
    tinymce_jquery: true
    selector: ".tinymce"
    language: %locale%
    theme:
        advanced:
            convert_urls: false
            entity_encoding: "raw"
            plugins: "anchor code image link lists media paste table"
            menubar: false
            statusbar: false
            toolbar: "undo redo | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | table code"
