stfalcon_tinymce:
    tinymce_jquery: true
    selector: ".tinymce"
    language: %locale%
    theme:
        simple:
            content_css: "/css/tinymce-body.css"
            convert_urls: false
            forced_root_block: false
            entity_encoding: "raw"
            plugins: "anchor link lists paste"
            menubar: false
            statusbar: false
            toolbar: "undo redo | bold italic | bullist numlist | link"
        advanced:
            content_css: "/css/tinymce-body.css"
            convert_urls: false
            forced_root_block: false
            entity_encoding: "raw"
            plugins: "anchor code image link lists media paste table"
            menubar: false
            statusbar: false
            toolbar: "undo redo | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | table code"
