stof_doctrine_extensions:
    default_locale: %locale%
    translation_fallback: true
    persist_default_translation: true
    orm:
        default:
            sluggable: true
            timestampable: true
            translatable: true
