portfolio_admin_project_list:
    locales:  { en: "/project/list", es: "/proyectos/lista" }
    defaults: { _controller: AitorGarciaPortfolioBundle:AdminProject:list }

portfolio_admin_project_create:
    locales:  { en: "/project/create", es: "/proyectos/crear" }
    defaults: { _controller: AitorGarciaPortfolioBundle:AdminProject:create }

portfolio_admin_project_edit:
    locales:  { en: "/project/{id}/edit", es: "/proyectos/{id}/modificar" }
    defaults: { _controller: AitorGarciaPortfolioBundle:AdminProject:edit }

portfolio_admin_project_delete:
    locales:  { en: "/project/{id}/delete", es: "/proyectos/{id}/eliminar" }
    defaults: { _controller: AitorGarciaPortfolioBundle:AdminProject:delete }

portfolio_admin_project_translation_edit:
    locales:  { en: "/project/{id}/translation/{transLocale}/edit", es: "/proyectos/{id}/traduccion/{transLocale}/modificar" }
    defaults: { _controller: AitorGarciaPortfolioBundle:AdminProject:translationEdit }

portfolio_admin_technology_list:
    locales:  { en: "/technology/list", es: "/tecnologias/lista" }
    defaults: { _controller: AitorGarciaPortfolioBundle:AdminTechnology:list }

portfolio_admin_technology_create:
    locales:  { en: "/technology/create", es: "/tecnologias/crear" }
    defaults: { _controller: AitorGarciaPortfolioBundle:AdminTechnology:create }

portfolio_admin_technology_edit:
    locales:  { en: "/technology/{id}/edit", es: "/tecnologias/{id}/modificar" }
    defaults: { _controller: AitorGarciaPortfolioBundle:AdminTechnology:edit }

portfolio_admin_technology_delete:
    locales:  { en: "/technology/{id}/delete", es: "/tecnologias/{id}/eliminar" }
    defaults: { _controller: AitorGarciaPortfolioBundle:AdminTechnology:delete }
