portfolio_project_list:
    locales:  { en: "/projects/{page}", es: "/proyectos/{page}" }
    defaults: { _controller: AitorGarciaPortfolioBundle:Project:list, page: 1 }
    requirements:
        page: \d+

portfolio_project_show:
    locales:  { en: "/projects/{slug}", es: "/proyectos/{slug}" }
    defaults: { _controller: AitorGarciaPortfolioBundle:Project:show }
