portfolio_project_list:
    locales:  { en: "/projects", es: "/proyectos" }
    defaults: { _controller: AitorGarciaPortfolioBundle:Project:list }

portfolio_project_show:
    locales:  { en: "/projects/{slug}", es: "/proyectos/{slug}" }
    defaults: { _controller: AitorGarciaPortfolioBundle:Project:show }
