blog_admin_post_list:
    locales:  { en: "/posts/{page}", es: "/entradas/{page}" }
    defaults: { _controller: AitorGarciaBlogBundle:AdminPost:list, page: 1 }
    requirements:
        page: \d+

blog_admin_post_create:
    locales:  { en: "/posts/create", es: "/entradas/crear" }
    defaults: { _controller: AitorGarciaBlogBundle:AdminPost:create }

blog_admin_post_edit:
    locales:  { en: "/posts/{id}/edit", es: "/entradas/{id}/modificar" }
    defaults: { _controller: AitorGarciaBlogBundle:AdminPost:edit }
    requirements:
        id: \d+

blog_admin_post_delete:
    locales:  { en: "/posts/{id}/delete", es: "/entradas/{id}/eliminar" }
    defaults: { _controller: AitorGarciaBlogBundle:AdminPost:delete }
    requirements:
        id: \d+

blog_admin_comment_list:
    locales:  { en: "/comments/{page}", es: "/comentarios/{page}" }
    defaults: { _controller: AitorGarciaBlogBundle:AdminComment:list, page: 1 }
    requirements:
        page: \d+

blog_admin_comment_edit:
    locales:  { en: "/comments/{id}/edit", es: "/comentarios/{id}/modificar" }
    defaults: { _controller: AitorGarciaBlogBundle:AdminComment:edit }
    requirements:
        id: \d+

blog_admin_comment_delete:
    locales:  { en: "/comments/{id}/delete", es: "/comentarios/{id}/eliminar" }
    defaults: { _controller: AitorGarciaBlogBundle:AdminComment:delete }
    requirements:
        id: \d+
