blog_admin_post_list:
    locales:  { en: "/posts/list", es: "/entradas/lista" }
    defaults: { _controller: AitorGarciaBlogBundle:AdminPost:list }

blog_admin_post_create:
    locales:  { en: "/posts/create", es: "/entradas/crear" }
    defaults: { _controller: AitorGarciaBlogBundle:AdminPost:create }

blog_admin_post_edit:
    locales:  { en: "/posts/{id}/edit", es: "/entradas/{id}/modificar" }
    defaults: { _controller: AitorGarciaBlogBundle:AdminPost:edit }
    requirements:
        page: \d+

blog_admin_post_delete:
    locales:  { en: "/posts/{id}/delete", es: "/entradas/{id}/eliminar" }
    defaults: { _controller: AitorGarciaBlogBundle:AdminPost:delete }
    requirements:
        page: \d+

blog_admin_comment_list:
    locales:  { en: "/comments/list", es: "/comentarios/lista" }
    defaults: { _controller: AitorGarciaBlogBundle:AdminComment:list }
