blog_post_list_by_tag:
    locales:  { en: "/blog-en/tag/{slug}/{page}", es: "/blog/etiqueta/{slug}/{page}" }
    defaults: { _controller: AitorGarciaBlogBundle:Post:listByTag, page: 1 }
    requirements:
        page: \d+

blog_post_feed:
    locales:  { en: "/blog-en/feed", es: "/blog/feed" }
    defaults: { _controller: AitorGarciaBlogBundle:Post:feed }

blog_post_list:
    locales:  { en: "/blog-en/{page}", es: "/blog/{page}" }
    defaults: { _controller: AitorGarciaBlogBundle:Post:list, page: 1 }
    requirements:
        page: \d+

blog_post_show:
    locales:  { en: "/blog-en/{slug}", es: "/blog/{slug}" }
    defaults: { _controller: AitorGarciaBlogBundle:Post:show }
