_admin_index:
    locales:  { de: "/", es: "/", en: "/" }
    pattern:  /
    defaults: { _controller: AitorGarciaMainBundle:Admin:preIndex }

admin_index:
    locales:  { en: "/home", es: "/portada" }
    defaults: { _controller: AitorGarciaMainBundle:Admin:index }
