admin_index:
    pattern:  /
    defaults: { _controller: PortfolioBundle:AdminDefault:index }

admin_project_list:
    pattern:  /project/list
    defaults: { _controller: PortfolioBundle:AdminProject:list }

admin_project_create:
    pattern:  /project/create
    defaults: { _controller: PortfolioBundle:AdminProject:create }

admin_project_edit:
    pattern:  /project/edit/{id}
    defaults: { _controller: PortfolioBundle:AdminProject:edit }

admin_project_delete:
    pattern:  /project/delete/{id}
    defaults: { _controller: PortfolioBundle:AdminProject:delete }
