admin_project_list:
    pattern:  /project/list
    defaults: { _controller: PortfolioBundle:AdminProject:list }

admin_project_create:
    pattern:  /project/create
    defaults: { _controller: PortfolioBundle:AdminProject:create }

admin_project_edit:
    pattern:  /project/{id}/edit
    defaults: { _controller: PortfolioBundle:AdminProject:edit }

admin_project_delete:
    pattern:  /project/{id}/delete
    defaults: { _controller: PortfolioBundle:AdminProject:delete }

admin_project_translation_edit:
    pattern:  /project/{id}/translation/{lang}/edit
    defaults: { _controller: PortfolioBundle:AdminProject:translationEdit }

admin_technology_list:
    pattern:  /technology/list
    defaults: { _controller: PortfolioBundle:AdminTechnology:list }

admin_technology_create:
    pattern:  /technology/create
    defaults: { _controller: PortfolioBundle:AdminTechnology:create }

admin_technology_edit:
    pattern:  /technology/{id}/edit
    defaults: { _controller: PortfolioBundle:AdminTechnology:edit }

admin_technology_delete:
    pattern:  /technology/{id}/delete
    defaults: { _controller: PortfolioBundle:AdminTechnology:delete }
