project_list:
    locales:  { en: "/projects", es: "/proyectos" }
    defaults: { _controller: AitorGarciaPortfolioBundle:Project:list }

project_show:
    locales:  { en: "/projects/{url}", es: "/proyectos/{url}" }
    defaults: { _controller: AitorGarciaPortfolioBundle:Project:show }

contact:
    locales:  { en: "/contact", es: "/contacto" }
    defaults: { _controller: AitorGarciaPortfolioBundle:Default:contact }

_portfolio_admin:
    resource: "@AitorGarciaPortfolioBundle/Resources/config/admin_routing.yml"
    prefix: /admin
    type: be_simple_i18n
