_index:
    pattern:  /
    defaults: { _controller: PortfolioBundle:Default:preIndex }

index:
    locales:  { en: "/home", es: "/portada" }
    defaults: { _controller: PortfolioBundle:Default:index }

project_list:
    locales:  { en: "/projects", es: "/proyectos" }
    defaults: { _controller: PortfolioBundle:Project:list }

project_show:
    locales:  { en: "/projects/{url}", es: "/proyectos/{url}" }
    defaults: { _controller: PortfolioBundle:Project:show }

contact:
    locales:  { en: "/contact", es: "/contacto" }
    defaults: { _controller: PortfolioBundle:Default:contact }
