index:
    pattern:  /
    defaults: { _controller: PortfolioBundle:Default:index }

project_list:
    pattern:  /projects
    defaults: { _controller: PortfolioBundle:Project:list }

project_show:
    pattern:  /projects/{url}
    defaults: { _controller: PortfolioBundle:Project:show }

contact:
    pattern: /contact
    defaults: { _controller: PortfolioBundle:Default:contact }
