services:
    aitorgarcia.translate_slug_listener.request:
        class: AitorGarcia\PortfolioBundle\EventListener\TranslateSlugListener
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
